name: "Run cypress"
description: "Run cypress."

inputs:
  base_url:
    description: "base url"
    required: true

runs:
  using: "composite"

  steps:
    - name: Cypress run with env
      uses: cypress-io/github-action@v6
      with:
          working-directory: ${{ github.action_path }}
      env:
        BASE_URL: ${{ inputs.base_url }}
