name: "Run cypress"
description: "Run cypress."

inputs:
  base_url:
    description: "base url"
    required: true

runs:
  using: "composite"

  steps:
    - name: list dir
      shell: bash
      run: ls -la ${{ github.action_path }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: "xdigu/cypress-test"

    - name: Cypress run with env
      uses: cypress-io/github-action@v6
      env:
        BASE_URL: ${{ inputs.base_url }}
