on:
  workflow_call:
    inputs:
      base_url:
        required: true
        type: string

env:
  WORK_DIR: cypress-test

jobs:
  cypress-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "xdigu/cypress-test"
          path: ${{ github.env.WORK_DIR }}
          ref: "main"

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        with:
          working-directory: ${{ github.env.WORK_DIR }}
        env:
          BASE_URL: ${{ inputs.base_url }}
