on:
  workflow_call:
    inputs:
      base_url:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        env:
          BASE_URL: ${{ inputs.base_url }}
