on:
  workflow_call:
    inputs:
      base_url:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # cache npm modules and Cypress binary folder
      # we can use "package-lock.json" as the key file
      # to make sure we use the precise Cypress version
      # (which is important when using ^ version in package.json)
      # see https://github.com/actions/cache
      - name: Cache npm and Cypress 📦
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress 📥
        run: npm install cypress@14.2.0 --save-dev

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        with:
          project: ./
        env:
          BASE_URL: ${{ inputs.base_url }}
