on:
  workflow_call:
    inputs:
      work_dir:
        required: true
        type: string
      base_url:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'xdigu/cypress-test'
          path: 'cypress-test'
          ref: 'main'

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        with:
          working-directory: "cypress-test"
        env:
          BASE_URL: ${{ inputs.base_url }}
